services: 
  bento:
    image: lewisdoesstuff/bento
    volumes:
      # Append Bento config location to below line as a single file
      - type: bind
        source: ./config.js
        target: /usr/share/nginx/html/config.js
    ports:
      # Replace host port 80 (left side) with desired port.
      - 8081:80
